### ISSUE TITLE
Command doesn't execute when npc is villager

### ISSUE THREAD

**Issue by FortStomper** [messageofdeath/CommandNPC#38]
Hi,
Im using the spigot 1.8.8 version and have used the cmdnpc plugin for a while. but I have this bug and I cant find anyone on the internet who has the same problem: if I had permissionex on the server and took out again, the commands on the villager npcs (player npc works), stop working. I disabled cmd on the villager but nothing works, eventhough it woked bevor I added and removed permissionsex. If I change that npcs type to player it works again and when i create a new npc type villager (after I removed the permissiones plugin and folder) it still doesnt work. When i want to execute the command, nothing happen, nothing is in the cmdtab  and nothing is said in the server via text. Can someone please help me? Thanks in advance,
Me

**Comment by madtomic** [comment]
You need a permission plugin to use any plugin that uses permission to
control what command a player can use. You are able to use it before
without PEX it is because you are playing as a OP. I recommend to use vault
and some permission plugin and try to give yourself the corresponding
permission for the command you want to use and see if it works for you
correctly.

**Comment by FortStomper** [comment]
Hey, know I just wrote this text a view minutes ago, but I found out what the problem was: another plugin: BootsByReaZe. I didn't Imagine that was the problem, sorry!
